// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	Done        bool
	UserID      pgtype.UUID
}

type User struct {
	ID   pgtype.UUID
	Name string
}
