version: "3"

tasks:
  run:
    cmds:
      - docker compose -f docker-compose.yaml up
    env:
      MY_UID:
        sh: id -u
      MY_GID:
        sh: id -g
    silent: true
  stop:
    cmds:
      - docker compose -f docker-compose.yaml down
    silent: true
  goose:
    env:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "postgresql://admin:admin@localhost:5432/postgres?sslmode=disable"
      GOOSE_MIGRATION_DIR: "db/migrations"
    cmds:
      - goose {{.CLI_ARGS}}
  sqlc:
    cmds:
      - sqlc generate
    silent: true
  gqlgen:
    cmds:
      - go run github.com/99designs/gqlgen generate
    silent: true
